### ISSUE TITLE
Correct inputs of the function

### ISSUE THREAD

**Issue by smtabatabaie** [0xcyphered/secp256k1-solidity#1]
Thanks very much for this and sorry if my question is amateurish, I'm a beginner in this field.
I'm trying to get the latest outgoing transaction of an address and then extract the public key. I've used Etherscan's API endpoint "txlist" and retrieved the latest transactions of an Ethereum address. And also used "eth_getTransactionByHash" API endpoint to get more details of the transaction. This is what I've got from these two endpoints and I was wondering which of these parameters is the correct input for your module. Thanks again
result of Etherscan's txlist API endpoint:
![Screen Shot 2023-01-28 at 10 40 13 PM](https://user-images.githubusercontent.com/2934801/215289311-35c9c8de-3ace-4f04-be75-4259fe557bf2.png)

result of Etherscan's eth_getTransactionByHash API endpoint:
![Screen Shot 2023-01-28 at 10 40 00 PM](https://user-images.githubusercontent.com/2934801/215289346-11afb0d8-15aa-4e8b-b606-77708de0dc3d.png)

**Comment by 0xcyphered** [comment]
For public key recovery we need R,S,V values of a ciphered message. I see they are inserted in `eth_getTransactionByHash` method result.

**Comment by smtabatabaie** [comment]
> For public key recovery we need R,S,V values of a ciphered message. I see they are inserted in `eth_getTransactionByHash` method result.

Thanks very much @0xcyphered , so R,S, and V are enough? because it seems the function in the script also gets a message. And if so (if it also needs the msg) what should I provide as the message? Thanks again very much

**Comment by 0xcyphered** [comment]
Your welcome. The pre-encrypted hashed message is also required for the process.
https://github.com/0xcyphered/secp256k1-solidity/blob/38bc2ac235837ee0a28908d0198f8509ed58ad65/contracts/SECP256K1.sol#L23

**Comment by 0xcyphered** [comment]
Your welcome. The message or most of the times hash of that is also required for the process.
https://github.com/0xcyphered/secp256k1-solidity/blob/38bc2ac235837ee0a28908d0198f8509ed58ad65/contracts/SECP256K1.sol#L23
